touch_element:
  disable:
    - if: IDF_VERSION_MAJOR <= 5 and IDF_VERSION_MINOR < 3
      reason: IDF version below v5.3 is not supported
    - if: IDF_TARGET not in ["esp32s2", "esp32s3"]
      reason: only supports esp32s2 and esp32s3
